on: 
  push:
    branches: [main]
  repository_dispatch:
    # Used by other repositories to trigger a deployment
    types: [trigger-deploy]
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --recursive --remote
      - name: build and deploy with Zola
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Authentication token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
